# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(help_text=b'ISO 3166-1 alpha-2 - two character country code', max_length=2)),
                ('independence_day', models.DateField(blank=True, null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text=b'Try and enter few some more lines')),
                ('architecture', models.TextField(blank=True)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Continent')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
