# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('help_text', models.CharField(help_text=b'Enter fully qualified name', max_length=64)),
                ('multiple_in_row', models.CharField(help_text=b'Help text for multiple', max_length=64)),
                ('multiple2', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('date_widget', models.DateField(blank=True, null=True)),
                ('datetime_widget', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
