# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='textfield',
            field=models.TextField(blank=True, help_text=b'Try and enter few some more lines', verbose_name=b'Autosized textfield'),
        ),
    ]
