# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_showcase_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='readonly_field',
            field=models.CharField(default=b'Some value here', max_length=127),
        ),
    ]
