# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_showcase_time_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating', models.SmallIntegerField(choices=[(1, b'Awesome'), (2, b'Good'), (3, b'Normal'), (4, b'Bad')], help_text=b'Choose wisely')),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating', models.SmallIntegerField(choices=[(1, b'Awesome'), (2, b'Good'), (3, b'Normal'), (4, b'Bad')], default=2)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='showcase',
            options={'verbose_name_plural': 'Showcase'},
        ),
        migrations.AlterField(
            model_name='showcase',
            name='time_only',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Time'),
        ),
        migrations.AddField(
            model_name='movie',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Showcase'),
        ),
        migrations.AddField(
            model_name='book',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Showcase'),
        ),
    ]
