# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20160303_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_public',
            new_name='is_released',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='is_public',
            new_name='is_released',
        ),
    ]
