# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20160305_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='collapsed_param',
            field=models.BooleanField(default=False),
        ),
    ]
