# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_showcase_collapsed_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='showcase',
            name='boolean_with_help',
            field=models.BooleanField(default=False, help_text=b'Boolean field with help text'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='choices',
            field=models.SmallIntegerField(choices=[(1, b'Tall'), (2, b'Normal'), (3, b'Short')], default=3, help_text=b'Help text'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='horizontal_choices',
            field=models.SmallIntegerField(choices=[(1, b'Awesome'), (2, b'Good'), (3, b'Normal'), (4, b'Bad')], default=1, help_text=b'Horizontal choices look like this'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='vertical_choices',
            field=models.SmallIntegerField(choices=[(1, b'Hot'), (2, b'Normal'), (3, b'Cold')], default=2, help_text=b'Some help on vertical choices'),
        ),
    ]
