# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20170211_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Country'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='country2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showcase_country2_set', to='demo.Country', verbose_name=b'asd'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='raw_id_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showcase_raw_set', to='demo.Country'),
        ),
    ]
