name: Django CI

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
        django-version: ['4.2']

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -e .
        pip install -q Django==${{ matrix.django-version }}
    - name: Run Tests
      run: |
        DJANGO_SETTINGS_MODULE=suit.tests.settings django-admin test suit
